FROM ubuntu:14.04
WORKDIR /nativebinaries

RUN apt update && apt -y install cmake gcc-multilib build-essential automake autopoint autoconf libtool git

COPY . /nativebinaries/

CMD ["/bin/bash", "-c", "/nativebinaries/build-native-linux.sh"]
