FROM ubuntu:14.04
WORKDIR /nativebinaries

RUN apt update && apt -y install cmake gcc-multilib build-essential automake autopoint autoconf libtool

RUN apt install -y wget && \
    wget http://us.archive.ubuntu.com/ubuntu/pool/main/g/gettext/autopoint_0.19.7-2ubuntu3_all.deb && \
    dpkg -i autopoint_0.19.7-2ubuntu3_all.deb

COPY . /nativebinaries/

CMD ["/bin/bash", "-c", "/nativebinaries/build-native-linux.sh"]
